COPY "\\Hayabusa\共有\開発物件\た\大宝家具\prg\COM\DLL\impelLib36\bin\ImpelLib3.dll" "\\Hayabusa\共有\開発物件\た\大宝家具\020_EXE"
COPY "\\Hayabusa\共有\開発物件\た\大宝家具\prg\COM\DLL\HanbaiComLib\bin\HanbaiComLib.dll" "\\Hayabusa\共有\開発物件\た\大宝家具\020_EXE"
COPY "\\Hayabusa\共有\開発物件\た\大宝家具\prg\COM\DLL\ImpelComLib\bin\ImpelComLib.dll" "\\Hayabusa\共有\開発物件\た\大宝家具\020_EXE"
COPY "\\Hayabusa\共有\開発物件\た\大宝家具\prg\COM\DLL\SearchWindow\bin\SearchWindow.dll" "\\Hayabusa\共有\開発物件\た\大宝家具\020_EXE"

pause
